-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--# INPUT 

-- follow this guide to add custom input devices 

-- https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs

hl.config({
    input = {
        kb_layout = "fr",
        numlock_by_default = true,
        touchpad = {
            natural_scroll = true,
            scroll_factor = 0.6,
            disable_while_typing = false,
        },
        follow_mouse = 1,
        sensitivity = 0,
    },
})

--# GESTURES (updated as of 0.51.0)

-- feel free to suggest more gestures

hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "horizontal",
    ["action"] = "workspace",
})

hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "vertical",
    ["action"] = "fullscreen",
})
