-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--

-- HYPRLAND CONFIGURATION

-- @GeodeArc 2025

--

local browser = "$(cat os.getenv(\"HOME\")/Dots/Options/browser)"

local terminal = "$(cat os.getenv(\"HOME\")/Dots/Options/terminal)"

-- kitty by default, ill make selection later maybe

-- PYWAL

-- source = config/colors.conf -> requires manual conversion
local colors = require("config.colors")


-- Symlinked from ~/.cache/wal/

-- SPECIFICS

-- source = config/apptype.conf -> requires manual conversion
local apptype = require("config.apptype")


-- Either GTK or QT

-- source = config/cursortheme.conf -> requires manual conversion
local cursortheme = require("config.cursortheme")


-- Changes based off light/dark theme.

-- source = config/player.conf -> requires manual conversion
local player = require("config.player")


-- Player seen on waybar, affects keybinds

-- HARDWARE

-- source = config/hardware/monitor.conf -> requires manual conversion
local monitor = require("config.hardware.monitor")


-- Monitors

-- source = config/hardware/input.conf -> requires manual conversion
local input = require("config.hardware.input")


-- Mouse, keyboard etc.

-- DEFAULTS

-- source = config/setup/envvars.conf -> requires manual conversion
local envvars = require("config.setup.envvars")


-- Environment Variables

-- source = config/setup/autostart.conf -> requires manual conversion
 local autostart = require("config.setup.autostart")


-- Apps that launch on startup

-- SPECIFICS

-- source = config/apptype.conf -> requires manual conversion
local apptype = require("config.apptype")

-- Either GTK or QT

-- source = config/cursortheme.conf -> requires manual conversion
local cursortheme = require("config.cursortheme")


-- Changes based off light/dark theme.

-- SOFTWARE

-- source = config/software/general.conf -> requires manual conversion
local general = require("config.software.general")


-- General Configuration

-- source = config/software/keybinds.conf -> requires manual conversion
local keybinds = require("config.software.keybinds")


-- Keyoard shortcuts

-- source = config/software/rules.conf -> requires manual conversion
local rules = require("config.software.rules")


-- Window specific rules

-- THEME SPECIFIC SETTINGS

-- source = theme.conf -> requires manual conversion
-- local theme = require("theme")
-- TODO: convert theme.conf to .lua and use require()
