-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- SPECIFIC OPTIONS OVERWRITTEN BY THIS THEME

-- LOOKS

-- source = config/looks/decor.conf -> requires manual conversion
-- local decor = require("config.looks.decor")
-- TODO: convert config/looks/decor.conf to .lua and use require()

-- Decoration (Blur, Rounding etc)

-- source = config/looks/animations.conf -> requires manual conversion
-- local animations = require("config.looks.animations")
-- TODO: convert config/looks/animations.conf to .lua and use require()

-- Animations

hl.config({
    decoration = {
        rounding = 25,
        blur = {
            enabled = true,
            size = 15,
            passes = 2,
        },
    },
})

hl.layer_rule({
    match = {
        namespace = "blur on",
    },
    match:namespace = "waybar",
})

hl.layer_rule({
    match = {
        namespace = "blur on",
    },
    match:namespace = "swaync-control-center",
})

hl.layer_rule({
    match = {
        namespace = "blur on",
    },
    match:namespace = "swaync-notification-window",
})

hl.layer_rule({
    match = {
        namespace = "blur on",
    },
    match:namespace = "rofi",
})

hl.layer_rule({
    match = {
        namespace = "blur on",
    },
    match:namespace = "swayosd",
})

hl.layer_rule({
    match = {
        namespace = "ignore_alpha 0.5",
    },
    match:namespace = "waybar",
})

hl.layer_rule({
    match = {
        namespace = "ignore_alpha 0.5",
    },
    match:namespace = "swaync-control-center",
})

hl.layer_rule({
    match = {
        namespace = "ignore_alpha 0.5",
    },
    match:namespace = "swaync-notification-window",
})

hl.layer_rule({
    match = {
        namespace = "ignore_alpha 0.5",
    },
    match:namespace = "rofi",
})

hl.layer_rule({
    match = {
        namespace = "ignore_alpha 0.5",
    },
    match:namespace = "swayosd",
})
