-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- SPECIFIC OPTIONS OVERWRITTEN BY THIS THEME

-- LOOKS

-- source = config/looks/decor.conf -> requires manual conversion
local decor = require("config.looks.decor")


-- Decoration (Blur, Rounding etc)

-- source = config/looks/animations.conf -> requires manual conversion
local animations = require("config.looks.animations")


-- Animations

hl.config({
    decoration = {
        rounding = 25,
        blur = {
            enabled = true,
            size = 15,
            passes = 2,
        },
    },
})

local apps = { "waybar", "swaync-control-center", "swaync-notification-window", "rofi", "swayosd" }

for _, app in ipairs(apps) do
    hl.layer_rule({ "blur", match = { namespace = app } })
    hl.layer_rule({ "ignorezero", match = { namespace = app } })
end
