-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local foreground = "rgba(e6e1cfCC)"

local foregroundfull = "rgb(e6e1cf)"

local background = "rgba(121113CC)"

local backgroundfull = "rgb(121113)"
