-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--# General configuration (see decor.conf for general styling settings) 

hl.config({
    general = {
        -- Resize when you drag the edge of a window
        resize_on_border = true,
        -- Tearing support, may fix glitching in some games
        allow_tearing = false,
        -- What layout is used (read wiki.hypr.land/Configuring/Dwindle-Layout/ and wiki.hypr.land/Configuring/Master-Layout/)
        layout = "dwindle",
    },
})

--# Dwindle specific settings

hl.config({
    dwindle = {
        -- pseudotile = true
        preserve_split = true,
        smart_split = false,
    },
})

--# Master layout settings

hl.config({
    master = {
        new_status = "master",
    },
})

--# Miscellaneous

hl.config({
    misc = {
        force_default_wallpaper = 1,
        disable_splash_rendering = true,
        disable_hyprland_logo = true,
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
        vrr = 0,
    },
})

hl.config({
    binds = {
        disable_keybind_grabbing = false,
    },
})

hl.config({
    xwayland = {
        enabled = true,
        force_zero_scaling = false,
        use_nearest_neighbor = false,
    },
})

hl.config({
    cursor = {
        sync_gsettings_theme = true,
        enable_hyprcursor = true,
    },
})
