-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--# DEFAULT MOD KEY

-- SUPER = Windows Key

local Mod = "SUPER"

local Mod2 = "ALT"


--# BASE APPS

hl.bind(Mod .. " + " .. "RETURN", hl.dsp.exec_cmd(terminal))

hl.bind(Mod .. " + " .. "E", hl.dsp.exec_cmd(fileManager))

hl.bind(Mod .. " + " .. "T", hl.dsp.exec_cmd(textEditor))

hl.bind(Mod .. " + " .. "B", hl.dsp.exec_cmd(browser))

hl.bind(Mod .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region -o " .. os.getenv("HOME") .. "/Pictures/Screenshots -f Screenshot_$(date \"+%Y-%m-%d_%H:%M:%S\" ).png -z"))
--# HYPRLAND MANAGEMENT

hl.bind(Mod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(Mod2 .. " + " .. "F4", hl.dsp.window.close())

hl.bind(Mod .. " + " .. "V", hl.dsp.window.float())

hl.bind(Mod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen({ mode = 1 }))

hl.bind(Mod .. " + " .. "P", hl.dsp.window.pseudo())

hl.bind(Mod2 .. " + " .. "CTRL" .. " + " .. "DELETE", hl.dsp.exec_cmd("pgrep -x uwsm >/dev/null && uwsm stop || hyprctl dispatch exit"))

hl.bind(Mod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

--# ROFI

hl.bind(Mod .. " + " .. "SPACE", hl.dsp.exec_cmd("~/.config/rofi/launcher.sh"))

hl.bind(Mod .. " + " .. "M", hl.dsp.exec_cmd("~/.config/rofi/mode.sh"))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("~/.config/rofi/powermenu.sh"))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("~/.config/rofi/screenshot.sh"))

hl.bind(Mod .. " + " .. "C", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))

hl.bind(Mod .. " + " .. "period", hl.dsp.exec_cmd("rofi -modi emoji -show emoji"))

--# WAYBAR

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "B", hl.dsp.exec_cmd("~/Dots/Scripts/Waybar/waybar.sh"))

hl.bind(Mod .. " + " .. "ALT" .. " + " .. "B", hl.dsp.exec_cmd("~/Dots/Scripts/Waybar/waybartoggle.sh"))

--# MAIN SCRIPTS

hl.bind(Mod .. " + " .. "K", hl.dsp.exec_cmd("$terminal less ~/Dots/Guide/default-binds"))

hl.bind(Mod .. " + " .. "I", hl.dsp.exec_cmd("$terminal " .. os.getenv("HOME") .. "/Dots/Scripts/Settings/settings.sh"))

--# OTHER APPS

hl.bind(Mod .. " + " .. "W", hl.dsp.exec_cmd("waypaper"))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("waypaper --random"))

hl.bind("CTRL + SHIFT + ESCAPE", hl.dsp.exec_cmd("resources"))

hl.bind(Mod .. " + " .. "D", hl.dsp.exec_cmd("vesktop"))

--# WORKSPACE MANAGEMENT (SUPER)

hl.bind(Mod .. " + " .. "code:10", hl.dsp.focus({ workspace = 1 }))

hl.bind(Mod .. " + " .. "code:11", hl.dsp.focus({ workspace = 2 }))

hl.bind(Mod .. " + " .. "code:12", hl.dsp.focus({ workspace = 3 }))

hl.bind(Mod .. " + " .. "code:13", hl.dsp.focus({ workspace = 4 }))

hl.bind(Mod .. " + " .. "code:14", hl.dsp.focus({ workspace = 5 }))

hl.bind(Mod .. " + " .. "code:15", hl.dsp.focus({ workspace = 6 }))

hl.bind(Mod .. " + " .. "code:16", hl.dsp.focus({ workspace = 7 }))

hl.bind(Mod .. " + " .. "code:17", hl.dsp.focus({ workspace = 8 }))

hl.bind(Mod .. " + " .. "code:18", hl.dsp.focus({ workspace = 9 }))

hl.bind(Mod .. " + " .. "code:19", hl.dsp.focus({ workspace = 10 }))

hl.bind(Mod .. " + " .. "EQUAL", hl.dsp.focus({ workspace = 11 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "EQUAL", hl.dsp.window.move({ workspace = 11 }))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:10", hl.dsp.exec_cmd("movetoworkspacesilent,1"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:11", hl.dsp.exec_cmd("movetoworkspacesilent,2"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:12", hl.dsp.exec_cmd("movetoworkspacesilent,3"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:13", hl.dsp.exec_cmd("movetoworkspacesilent,4"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:14", hl.dsp.exec_cmd("movetoworkspacesilent,5"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:15", hl.dsp.exec_cmd("movetoworkspacesilent,6"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:16", hl.dsp.exec_cmd("movetoworkspacesilent,7"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:17", hl.dsp.exec_cmd("movetoworkspacesilent,8"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:18", hl.dsp.exec_cmd("movetoworkspacesilent,9"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "code:18", hl.dsp.exec_cmd("movetoworkspacesilent,10"))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "EQUAL", hl.dsp.exec_cmd("movetoworkspacesilent,11"))

hl.bind(Mod .. " + " .. "left", hl.dsp.focus({ workspace = "r-1" }))

hl.bind(Mod .. " + " .. "right", hl.dsp.focus({ workspace = "r+1" }))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.window.move({ direction = "left" , follow = false}))

hl.bind(Mod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.window.move({ direction = "right" , follow = false}))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))

hl.bind(Mod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))

--# WINDOW MANAGEMENT (ALT)

hl.bind(Mod2 .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(Mod2 .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(Mod2 .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(Mod2 .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(Mod2 .. " + " .. "TAB", hl.dsp.window.cycle_next())

hl.bind(Mod .. " + " .. "TAB", hl.dsp.window.cycle_next({ next = false }))

hl.bind(Mod2 .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))

hl.bind(Mod2 .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))

hl.bind(Mod2 .. " + " .. "CTRL" .. " + " .. "up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))

hl.bind(Mod2 .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

hl.bind(Mod2 .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))

hl.bind(Mod2 .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))

hl.bind(Mod2 .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "up" }))

hl.bind(Mod2 .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "down" }))

--# DRAGGING/RESIZING

hl.bind(Mod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(Mod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

--# MULTIMEDIA KEYS

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume 2"), { repeating = true, locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume -2"), { repeating = true, locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { repeating = true, locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness +5"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness -5"), { repeating = true, locked = true })

hl.bind("CAPS + Caps_Lock", hl.dsp.exec_cmd("swayosd-client --caps-lock"), { repeating = true, locked = true })

-- gnome-calculator isnt installed by default, install it or change it to something else

hl.bind("XF86Calculator", hl.dsp.exec_cmd("gnome-calculator"))

-- $player can be all, or defined media source seen on your waybar. you can change the defined player through settings.

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next $player"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause $player"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause $player"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous $player"), { locked = true })

hl.bind("CAPS + Caps_Lock", hl.dsp.exec_cmd("swayosd-client --caps-lock"))
