-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--# WINDOW RULES

--# XWAYLAND FIXES (default)

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

--# IGNORE MAXIMIZE REQUESTS (default)

hl.window_rule({
    name  = "suppress_event_maxim_16",
    match = {
        class = ".*",
    },
    suppress_event = "maximize"
})

--# Hyprland-run (default)

hl.window_rule({
    name  = "move_20_monitor_h-12_19",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

--# FLOAT APPS

hl.window_rule({
    name  = "float_on_22",
    match = {
        class = "org.pulseaudio.pavucontrol",
    },
    float = true,
    size = { 1150, 600 },
    center = true,
})

hl.window_rule({
    name  = "float_on_23",
    match = {
        class = "blueman-manager",
    },
    float = true,
    size = { 800, 550 },
    center = true,
})

hl.window_rule({
    name  = "float_on_24",
    match = {
        class = "nm-connection-editor",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name  = "float_on_25",
    match = {
        class = "waypaper",
    },
    float = true,
    size = { 800, 600 },
    center = true,
})

hl.window_rule({
    name  = "float_on_26",
    match = {
        title = "Calculator",
    },
    float = true,
    size = { 380, 600 },
    center = true,
})

hl.window_rule({
    name  = "float_on_27",
    match = {
        class = "net.nokyan.Resources",
    },
    float = true,
    size = { 1150, 600 },
    center = true,
})

--# FILE PICKER FLOAT (assumes gtk file picker sorry)

hl.window_rule({
    name  = "float_on_30",
    match = {
        class = "xdg-desktop-portal-gtk",
    },
    float = true,
    size = { 1150, 600 },
    center = true,
})

--# BROWSER PICTURE-IN-PICTURE

hl.window_rule({
    name  = "float_on_33",
    match = {
        title = "Picture-in-Picture",
    },
    float = true,
    pin = true,
    size = { 800, 450 },
    move = { 0, 0 },
})

--# WORKSPACE RULES

--# Dont have any workspace rules yet for these dotfiles

--# LAYER RULES

--# All theme related layerrules are in the theme.conf file. Add custom ones below
