-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    animations = {
        enabled = true,
    },
})
hl.curve("fastOut", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1 } },
})
hl.curve("quick", {
    type = "bezier",
    points = { { 0.15, 0 }, { 0.1, 1 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 2, bezier = "fastOut", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2, bezier = "fastOut", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2, bezier = "fastOut", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 2, bezier = "fastOut" })
hl.animation({ leaf = "fade", enabled = true, speed = 2, bezier = "quick" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 3, bezier = "fastOut", style = "slide" })
