-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'










-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("$polkitAgent")
    hl.exec_cmd("systemctl --user start $polkitagent")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("swayosd-server &")
    hl.exec_cmd("swaync &")
    hl.exec_cmd(os.getenv("HOME") .. "/Dots/Scripts/Hyprland/startup.sh")
end)
