-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Cursor theme/size

hl.env("XCURSOR_THEME", cursortheme)

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_THEME", cursortheme)

hl.env("HYPRCURSOR_SIZE", 24)

-- QT

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- *fix* wayland blurriness (https://wiki.hypr.land/Configuring/XWayland/#hidpi-xwayland)

-- Comment this if you are experiencing issues with electron apps

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
